cuda: True
do_train: True
do_valid: False # don't validate formulation
do_test: True

domain: wn 
kg_path: ../save/data/wnkg 
q_path:  ../save/data/wnQ

hidden_dim: 300
model: vec 
lr: 0.001 
krl_train_steps: 100000 
valid_steps: 5000 
